[project]
name = "luna-bot-discord"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord-py>=2.5.2",
    "dnspython>=2.7.0",
    "pymongo>=4.13.0",
    "python-dotenv>=1.1.0",
]
